-- MySQL Script generated by MySQL Workbench
-- sáb 29 jul 2017 19:08:46 CDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `id` VARCHAR(255) NOT NULL,
  `usuario` VARCHAR(255) NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `celular` VARCHAR(20) NOT NULL,
  `fechaCreacion` DATE NULL,
  `ultimoLogin` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MatchMaker`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MatchMaker` (
  `usuarioId` VARCHAR(255) NOT NULL,
  `coordinadoraId` VARCHAR(255) NULL,
  `comision` DOUBLE NULL,
  PRIMARY KEY (`usuarioId`),
  INDEX `fk_MatchMaker_MatchMaker1_idx` (`coordinadoraId` ASC),
  CONSTRAINT `fk_MatchMaker_Usuarios1`
    FOREIGN KEY (`usuarioId`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MatchMaker_MatchMaker1`
    FOREIGN KEY (`coordinadoraId`)
    REFERENCES `mydb`.`MatchMaker` (`usuarioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empresa` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `direccion` VARCHAR(255) NULL,
  `MatchMaker_usuarioId` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `MatchMaker_usuarioId`),
  INDEX `fk_Empresa_MatchMaker1_idx` (`MatchMaker_usuarioId` ASC),
  CONSTRAINT `fk_Empresa_MatchMaker1`
    FOREIGN KEY (`MatchMaker_usuarioId`)
    REFERENCES `mydb`.`MatchMaker` (`usuarioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Evento` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empresaId` INT NOT NULL,
  `textoAMostrar` VARCHAR(255) NULL,
  `descripcion` LONGTEXT NULL,
  `fecha` DATE NULL,
  `duracion` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Evento_Empresa1_idx` (`empresaId` ASC),
  CONSTRAINT `fk_Evento_Empresa1`
    FOREIGN KEY (`empresaId`)
    REFERENCES `mydb`.`Empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EstatusCliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`EstatusCliente` (
  `estatusCliente` INT NOT NULL AUTO_INCREMENT,
  `texto` VARCHAR(255) NULL,
  `activo` TINYINT NULL,
  PRIMARY KEY (`estatusCliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cuestionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cuestionario` (
  `id` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CuestionarioConstestadoUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CuestionarioConstestadoUsuario` (
  `idCuestionario` INT NOT NULL,
  `fecha` DATE NULL,
  PRIMARY KEY (`idCuestionario`),
  INDEX `fk_Cuestionario_has_Usuarios_Cuestionario1_idx` (`idCuestionario` ASC),
  CONSTRAINT `fk_Cuestionario_has_Usuarios_Cuestionario1`
    FOREIGN KEY (`idCuestionario`)
    REFERENCES `mydb`.`Cuestionario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `usuarioId` VARCHAR(255) NOT NULL,
  `estatus` INT NOT NULL,
  `cuestionarioContestado` INT NULL,
  PRIMARY KEY (`usuarioId`),
  INDEX `fk_Cliente_EstatusCliente1_idx` (`estatus` ASC),
  INDEX `fk_Cliente_CuestionarioConstestadoUsuario1_idx` (`cuestionarioContestado` ASC),
  CONSTRAINT `fk_Cliente_Usuarios1`
    FOREIGN KEY (`usuarioId`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_EstatusCliente1`
    FOREIGN KEY (`estatus`)
    REFERENCES `mydb`.`EstatusCliente` (`estatusCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_CuestionarioConstestadoUsuario1`
    FOREIGN KEY (`cuestionarioContestado`)
    REFERENCES `mydb`.`CuestionarioConstestadoUsuario` (`idCuestionario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Encuentro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Encuentro` (
  `id` INT NOT NULL,
  `usuario1Id` VARCHAR(255) NOT NULL,
  `usuario2Id` VARCHAR(255) NOT NULL,
  `fecha` DATE NULL,
  `usuario1DeseaConocer` TINYINT NULL,
  `razonUsuario1` MEDIUMTEXT NULL,
  `usuario2DeseaConocer` TINYINT NULL,
  `razonUsuario2` MEDIUMTEXT NULL,
  `concretada` TINYINT NULL,
  `cancelado` TINYINT NULL,
  `motivoCancelacion` VARCHAR(255) NULL,
  `usuarioCanceloId` INT NULL,
  `calificacionLugar` INT NULL,
  `recomendariasLugar` TINYINT NULL,
  PRIMARY KEY (`id`, `usuario1Id`, `usuario2Id`),
  INDEX `fk_Encuentro_Cliente1_idx` (`usuario1Id` ASC),
  INDEX `fk_Encuentro_Cliente2_idx` (`usuario2Id` ASC),
  CONSTRAINT `fk_Encuentro_Cliente1`
    FOREIGN KEY (`usuario1Id`)
    REFERENCES `mydb`.`Cliente` (`usuarioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Encuentro_Cliente2`
    FOREIGN KEY (`usuario2Id`)
    REFERENCES `mydb`.`Cliente` (`usuarioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoPendiente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoPendiente` (
  `id` VARCHAR(45) NOT NULL,
  `nombreADesplegar` VARCHAR(255) NULL,
  `prioridad` INT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pendiente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pendiente` (
  `id` INT NOT NULL,
  `descripcion` MEDIUMTEXT NOT NULL,
  `numeroAMarcar` VARCHAR(20) NULL,
  `tipoPendiente` VARCHAR(45) NOT NULL,
  `matchMakerId` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `matchMakerId`),
  INDEX `fk_Pendiente_tipoPendiente1_idx` (`tipoPendiente` ASC),
  INDEX `fk_Pendiente_MatchMaker1_idx` (`matchMakerId` ASC),
  CONSTRAINT `fk_Pendiente_tipoPendiente1`
    FOREIGN KEY (`tipoPendiente`)
    REFERENCES `mydb`.`TipoPendiente` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pendiente_MatchMaker1`
    FOREIGN KEY (`matchMakerId`)
    REFERENCES `mydb`.`MatchMaker` (`usuarioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrevista`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entrevista` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuarioId` VARCHAR(255) NOT NULL,
  `matchMakerId` VARCHAR(255) NOT NULL,
  `fecha` DATE NULL,
  `noDeReprogramaciones` INT NULL,
  PRIMARY KEY (`id`, `usuarioId`, `matchMakerId`),
  INDEX `fk_Entrevista_Cliente1_idx` (`usuarioId` ASC),
  INDEX `fk_Entrevista_MatchMaker1_idx` (`matchMakerId` ASC),
  CONSTRAINT `fk_Entrevista_Cliente1`
    FOREIGN KEY (`usuarioId`)
    REFERENCES `mydb`.`Cliente` (`usuarioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entrevista_MatchMaker1`
    FOREIGN KEY (`matchMakerId`)
    REFERENCES `mydb`.`MatchMaker` (`usuarioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recomendacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recomendacion` (
  `id` INT NOT NULL,
  `entrevistaId` INT NOT NULL,
  `descripcion` LONGTEXT NOT NULL,
  `fecha` DATE NOT NULL,
  `haSidoVista` TINYINT NULL,
  PRIMARY KEY (`id`, `entrevistaId`),
  INDEX `fk_Recomendacion_Entrevista1_idx` (`entrevistaId` ASC),
  CONSTRAINT `fk_Recomendacion_Entrevista1`
    FOREIGN KEY (`entrevistaId`)
    REFERENCES `mydb`.`Entrevista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TipoCorreo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TipoCorreo` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Correo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Correo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empresaId` INT NOT NULL,
  `tipoCorreo` INT NOT NULL,
  `contenido` LONGTEXT NOT NULL,
  `titulo` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Correo_TipoCorreo1_idx` (`tipoCorreo` ASC),
  INDEX `fk_Correo_Empresa1_idx` (`empresaId` ASC),
  CONSTRAINT `fk_Correo_TipoCorreo1`
    FOREIGN KEY (`tipoCorreo`)
    REFERENCES `mydb`.`TipoCorreo` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Correo_Empresa1`
    FOREIGN KEY (`empresaId`)
    REFERENCES `mydb`.`Empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Membresia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Membresia` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empresaId` INT NOT NULL,
  `textoAMostrar` VARCHAR(255) NULL,
  `descripcion` LONGTEXT NULL,
  `numeroDeEncuentros` INT NULL,
  `costo` DOUBLE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Membresia_Empresa1_idx` (`empresaId` ASC),
  CONSTRAINT `fk_Membresia_Empresa1`
    FOREIGN KEY (`empresaId`)
    REFERENCES `mydb`.`Empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Alianza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Alianza` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empresaId` INT NOT NULL,
  `empresa` VARCHAR(255) NULL,
  `direccion` VARCHAR(255) NULL,
  `telefono` VARCHAR(45) NULL,
  `paginaWeb` VARCHAR(255) NULL,
  `beneficios` MEDIUMTEXT NULL,
  PRIMARY KEY (`id`, `empresaId`),
  INDEX `fk_Alianza_Empresa1_idx` (`empresaId` ASC),
  CONSTRAINT `fk_Alianza_Empresa1`
    FOREIGN KEY (`empresaId`)
    REFERENCES `mydb`.`Empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gasto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gasto` (
  `id` INT NOT NULL,
  `descripcion` LONGTEXT NULL,
  `monto` DOUBLE NULL,
  `esRecurrente` TINYINT NULL,
  `validoDesde` DATE NULL,
  `empresaId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Gasto_Empresa1_idx` (`empresaId` ASC),
  CONSTRAINT `fk_Gasto_Empresa1`
    FOREIGN KEY (`empresaId`)
    REFERENCES `mydb`.`Empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Zona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Zona` (
  `id` INT NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `empresaId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Zona_Empresa1_idx` (`empresaId` ASC),
  CONSTRAINT `fk_Zona_Empresa1`
    FOREIGN KEY (`empresaId`)
    REFERENCES `mydb`.`Empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Venta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descripcion` LONGTEXT NULL,
  `usuarioId` INT ZEROFILL NOT NULL,
  `monto` DOUBLE NULL,
  `empresaId` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Venta_Empresa1_idx` (`empresaId` ASC),
  CONSTRAINT `fk_Venta_Empresa1`
    FOREIGN KEY (`empresaId`)
    REFERENCES `mydb`.`Empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Accion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Accion` (
  `id` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(255) NULL,
  `accionATomar` VARCHAR(255) NULL,
  `textoAMostrar` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Multimedia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Multimedia` (
  `url` VARCHAR(255) NOT NULL,
  `tipo` VARCHAR(255) NULL,
  PRIMARY KEY (`url`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Preferencias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Preferencias` (
  `haVistotutorial` INT NOT NULL,
  `deseaQueAparezcaTutorial` VARCHAR(45) NULL,
  `usuarioId` VARCHAR(255) NOT NULL,
  INDEX `fk_Preferencias_Usuarios1_idx` (`usuarioId` ASC),
  PRIMARY KEY (`usuarioId`),
  CONSTRAINT `fk_Preferencias_Usuarios1`
    FOREIGN KEY (`usuarioId`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuarios_has_Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuarios_has_Usuarios` (
  `Usuarios_id` INT NOT NULL,
  `Usuarios_id1` INT NOT NULL,
  PRIMARY KEY (`Usuarios_id`, `Usuarios_id1`),
  INDEX `fk_Usuarios_has_Usuarios_Usuarios1_idx` (`Usuarios_id1` ASC),
  INDEX `fk_Usuarios_has_Usuarios_Usuarios_idx` (`Usuarios_id` ASC),
  CONSTRAINT `fk_Usuarios_has_Usuarios_Usuarios`
    FOREIGN KEY (`Usuarios_id`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_has_Usuarios_Usuarios1`
    FOREIGN KEY (`Usuarios_id1`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Perfil`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Perfil` (
  `id` INT NOT NULL,
  `sexo` VARCHAR(1) NULL,
  `preferencia` VARCHAR(45) NULL,
  `edad` INT(3) NULL,
  `usuarioId` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Perfil_Cliente1_idx` (`usuarioId` ASC),
  CONSTRAINT `fk_Perfil_Cliente1`
    FOREIGN KEY (`usuarioId`)
    REFERENCES `mydb`.`Cliente` (`usuarioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Retroalimentacion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Retroalimentacion` (
  `id` INT NOT NULL,
  `texto` LONGTEXT NOT NULL,
  `calificacion` INT NOT NULL,
  `volveriaASalir` TINYINT NULL,
  `encuentrioId` INT NOT NULL,
  `usuarioId` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`, `encuentrioId`, `usuarioId`),
  INDEX `fk_Retroalimentacion_Encuentro1_idx` (`encuentrioId` ASC, `usuarioId` ASC),
  CONSTRAINT `fk_Retroalimentacion_Encuentro1`
    FOREIGN KEY (`encuentrioId`)
    REFERENCES `mydb`.`Encuentro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`accionesDeUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`accionesDeUsuario` (
  `accionId` VARCHAR(45) NOT NULL,
  `Usuarios_id` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`accionId`, `Usuarios_id`),
  INDEX `fk_Accion_has_Usuarios_Accion1_idx` (`accionId` ASC),
  INDEX `fk_accionesDeUsuario_Usuarios1_idx` (`Usuarios_id` ASC),
  CONSTRAINT `fk_Accion_has_Usuarios_Accion1`
    FOREIGN KEY (`accionId`)
    REFERENCES `mydb`.`Accion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_accionesDeUsuario_Usuarios1`
    FOREIGN KEY (`Usuarios_id`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Lugar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Lugar` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `empresaId` INT NOT NULL,
  `nombre` VARCHAR(255) NULL,
  `tipo` VARCHAR(45) NULL,
  `tipoCocina` VARCHAR(45) NULL,
  `rangoDePrecios` VARCHAR(45) NULL,
  `estado` VARCHAR(45) NULL,
  `ciudad` VARCHAR(45) NULL,
  `direccion` VARCHAR(255) NULL,
  `horario` VARCHAR(45) NULL,
  `telefono` VARCHAR(20) NULL,
  `email` VARCHAR(255) NULL,
  `logotipo` VARCHAR(255) NULL,
  `calificacion` DOUBLE NULL,
  PRIMARY KEY (`id`, `empresaId`),
  INDEX `fk_Lugar_Empresa1_idx` (`empresaId` ASC),
  CONSTRAINT `fk_Lugar_Empresa1`
    FOREIGN KEY (`empresaId`)
    REFERENCES `mydb`.`Empresa` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Propuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Propuesta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `encuentroId` INT NOT NULL,
  `usuarioPropone` VARCHAR(255) NOT NULL,
  `lugarId` INT NOT NULL,
  `fecha` DATE NULL,
  `hora` VARCHAR(10) NULL,
  `aceptada` TINYINT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Propuesta_Lugar1_idx` (`lugarId` ASC),
  INDEX `fk_Propuesta_Encuentro1_idx` (`encuentroId` ASC, `usuarioPropone` ASC),
  CONSTRAINT `fk_Propuesta_Lugar1`
    FOREIGN KEY (`lugarId`)
    REFERENCES `mydb`.`Lugar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Propuesta_Encuentro1`
    FOREIGN KEY (`encuentroId` , `usuarioPropone`)
    REFERENCES `mydb`.`Encuentro` (`id` , `usuario1Id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `usuarioId` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`usuarioId`),
  CONSTRAINT `fk_Admin_Usuarios1`
    FOREIGN KEY (`usuarioId`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MultimediasDeUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MultimediasDeUsuario` (
  `usuarioId` VARCHAR(255) NOT NULL,
  `multimediaId` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`usuarioId`, `multimediaId`),
  INDEX `fk_Usuario_has_Multimedia_Multimedia1_idx` (`multimediaId` ASC),
  INDEX `fk_Usuario_has_Multimedia_Usuario1_idx` (`usuarioId` ASC),
  CONSTRAINT `fk_Usuario_has_Multimedia_Usuario1`
    FOREIGN KEY (`usuarioId`)
    REFERENCES `mydb`.`Usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_has_Multimedia_Multimedia1`
    FOREIGN KEY (`multimediaId`)
    REFERENCES `mydb`.`Multimedia` (`url`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Entrevista_has_Multimedia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Entrevista_has_Multimedia` (
  `entrevistaId` INT NOT NULL,
  `multimediaId` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`entrevistaId`, `multimediaId`),
  INDEX `fk_Entrevista_has_Multimedia_Multimedia1_idx` (`multimediaId` ASC),
  INDEX `fk_Entrevista_has_Multimedia_Entrevista1_idx` (`entrevistaId` ASC),
  CONSTRAINT `fk_Entrevista_has_Multimedia_Entrevista1`
    FOREIGN KEY (`entrevistaId`)
    REFERENCES `mydb`.`Entrevista` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Entrevista_has_Multimedia_Multimedia1`
    FOREIGN KEY (`multimediaId`)
    REFERENCES `mydb`.`Multimedia` (`url`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`membresiasUsuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`membresiasUsuario` (
  `usuarioId` VARCHAR(255) NOT NULL,
  `membresiaId` INT NOT NULL,
  `activa` TINYINT NULL,
  `fechaCreacion` DATE NULL,
  `suspendida` TINYINT NULL,
  `costo` DOUBLE NULL,
  PRIMARY KEY (`usuarioId`, `membresiaId`),
  INDEX `fk_Cliente_has_Membresia_Membresia1_idx` (`membresiaId` ASC),
  INDEX `fk_Cliente_has_Membresia_Cliente1_idx` (`usuarioId` ASC),
  CONSTRAINT `fk_Cliente_has_Membresia_Cliente1`
    FOREIGN KEY (`usuarioId`)
    REFERENCES `mydb`.`Cliente` (`usuarioId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Cliente_has_Membresia_Membresia1`
    FOREIGN KEY (`membresiaId`)
    REFERENCES `mydb`.`Membresia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`multimediaLugar`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`multimediaLugar` (
  `lugarId` INT NOT NULL,
  `Multimedia_url` VARCHAR(255) NOT NULL,
  `activa` TINYINT NULL,
  PRIMARY KEY (`lugarId`, `Multimedia_url`),
  INDEX `fk_Lugar_has_Multimedia_Multimedia1_idx` (`Multimedia_url` ASC),
  INDEX `fk_Lugar_has_Multimedia_Lugar1_idx` (`lugarId` ASC),
  CONSTRAINT `fk_Lugar_has_Multimedia_Lugar1`
    FOREIGN KEY (`lugarId`)
    REFERENCES `mydb`.`Lugar` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Lugar_has_Multimedia_Multimedia1`
    FOREIGN KEY (`Multimedia_url`)
    REFERENCES `mydb`.`Multimedia` (`url`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
